-- DROP and CREATE orders TABLE
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
id SERIAL PRIMARY KEY NOT NULL,
total INT,
CONSTRAINT fk_user FOREIGN KEY(id) REFERENCES users(id),
completed BOOLEAN DEFAULT FALSE
);